# Generated by Django 5.0.14 on 2026-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medname", models.CharField(max_length=200)),
                ("generic", models.CharField(max_length=200)),
                ("totaldose", models.IntegerField()),
                ("dose1", models.IntegerField()),
                ("dose2", models.IntegerField()),
                ("dose3", models.IntegerField()),
                ("whatfor", models.TextField()),
                ("sideeffects", models.TextField()),
            ],
        ),
    ]
