# Generated by Django 5.0.14 on 2026-09-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0002_medspost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="medspost",
            name="frequency",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medspost",
            name="type",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
