# Generated by Django 5.0.14 on 2026-09-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mood", models.IntegerField()),
                ("feelings", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
