# Generated by Django 5.0.14 on 2026-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sleepp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(max_length=200)),
                ("hourssleep", models.IntegerField()),
                ("notes", models.CharField(max_length=400)),
            ],
        ),
    ]
