# Generated by Django 5.0.14 on 2026-09-21 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleep", "0002_alter_sleepp_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sleepp",
            new_name="Sleep",
        ),
    ]
