# Generated by Django 5.0.14 on 2026-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=200)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("Anxiety", models.IntegerField()),
                ("Depression", models.IntegerField()),
                ("Mania", models.IntegerField()),
                ("Paranoia", models.IntegerField()),
                ("IdeasOfReference", models.IntegerField()),
                ("Hallucinations", models.IntegerField()),
                ("Fatigue", models.IntegerField()),
                ("Insomnia", models.IntegerField()),
                ("Restlessness", models.IntegerField()),
                ("Agitation", models.IntegerField()),
                ("WristPain", models.IntegerField()),
                ("ShoulderPain", models.IntegerField()),
            ],
        ),
    ]
